# Generated by Django 4.2.3 on 2023-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_branche'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media')),
                ('starting', models.FloatField(max_length=6)),
                ('haircut', models.FloatField(max_length=6)),
                ('beard_trim', models.FloatField(max_length=6)),
                ('razor_cut', models.FloatField(max_length=6)),
                ('shaves', models.FloatField(max_length=6)),
                ('styling_color', models.FloatField(max_length=6)),
            ],
        ),
    ]
